In [4]:
# Append in ndarray 
# 1-D

import numpy as np

# Create an initial array
arr = np.array([1, 2, 3])
print(arr, id(arr))

# Append a single value
arr2 = np.append(arr, 4)
print(arr2, id(arr2))  # Output: [1 2 3 4]
arr2[0] = 100
# Append multiple values
arr = np.append(arr, [5, 6])
print(arr, id(arr))  # Output: [1 2 3 4 5 6]


[1 2 3] 4433403536
[1 2 3 4] 4516906352
[1 2 3 5 6] 4516905968


In [9]:
# 2-D
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Append a row
new_row = np.array([[7, 8, 9]])
arr_2d = np.append(arr_2d, new_row, axis=0)
print(arr_2d)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# Append a column
new_column = np.array([[10], [11], [0]])
arr_2d = np.append(arr_2d, new_column, axis=1)
print(arr_2d)
# Output:
# [[ 1  2  3 10]
#  [ 4  5  6 11]
#  [ 7  8  9  0]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9  0]]


In [1]:
import numpy as np

In [8]:
lst = [[2, 4], [5, 3]]

arr = lst.copy()
del arr[0][0]

print(f'{arr=}')
print(f'{lst=}')

arr=[[4], [5, 3]]
lst=[[2, 4], [5, 3]]


In [15]:
lst = [[2, 4], [5, 3]]
arr = np.array(lst)
# out = arr.flatten()
out = np.ravel(arr)
arr[0][0] = 100
print(out)

# [2, 4, 5, 3]

[100   4   5   3]


In [10]:
import numpy as np

array = np.array([[0, 2, 1998],
                  [12, 0, 1212],
                  [21, 0, 0],
                  [7, 0, 2019]])

print(array.astype(bool)[0])
print(array)

[False  True  True]
[[   0    2 1998]
 [  12    0 1212]
 [  21    0    0]
 [   7    0 2019]]


In [11]:
import numpy as np

array = np.array([[0, 2, 1998],
                  [12, 0, 1212],
                  [21, 0, 0],
                  [7, 0, 2019]])

print(array == 0)
print(array[0])

[[ True False False]
 [False  True False]
 [False  True  True]
 [False  True False]]
[   0    2 1998]
