In [8]:
import numpy as np

arr = np.array([3, 5, 6, 7, 5, 7])

out = arr.reshape((3, 2))
print(out)
print(arr)


[[3 5]
 [6 7]
 [5 7]]
[3 5 6 7 5 7]


In [14]:
arr = np.arange(1, 10, 0)
print(arr)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [21]:
import matplotlib.pyplot as plt
import numpy as np 

arr = np.arange(0, 10, .1)

data_sin = np.sin(arr)
data_cos = np.cos(arr)
plt.plot(arr, data_sin)
plt.plot(arr, data_cos)
plt.show()



In [22]:
a = np.array([0,30,45,60,90])   
print(np.sin(a))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
